apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: video-tool-app
  name: video-tool-app
spec:
  resources:
    limits:
      cpu: "1000m"
      memory: "1000Mi"
  source:
    git:
      ref: master
      uri: https://github.com/Pallav695193/Video-Copy.git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
  triggers:
    - github:
        secret: secret
      type: GitHub
    - generic:
        secret: secret
      type: Generic
    - bitbucket:
        secret: secret
      type: Bitbucket
